#!/bin/bash
sudo apt -y update 
sudo apt -y upgrade
curl -fsSL https://get.docker.com -o get-docker.sh
sudo sh get-docker.sh
sudo groupadd docker
sudo usermod -aG docker ubuntu
sudo apt-get -y install python3-pip
pip3 --version
git clone https://github.com/JamesWRC/pythonAPI.git
cd pythonAPI
docker build --force-rm=true -t pythonapi:latest .
docker run --name python-api-spot-instance-example --restart=always -p 80:80 pythonapi:latest
